gridworld:
  Horizon: 1000
  Action_space: cardinal_moves  # Possible values: cardinal_moves, queens_moves
  Layout:
    - [., ., ., ., s, ., ., ., .]
    - [., w, w, ., w, ., w, w, .]
    - [., ., w, ., ., t, w, ., .]
    - [., w, w, w, w, ., w, ., .]
    - [., ., ., w, ., ., w, ., w]
    - [t, w, w, ., ., w, ., ., t]
  Rewards:
    - [., ., ., ., ., ., ., ., .]
    - [., w, w, ., w, ., w, w, .]
    - [., ., w, ., ., 10, w, ., .]
    - [., w, w, w, w, ., w, ., .]
    - [., ., ., w, ., ., w, ., w]
    - [2, w, w, ., ., w, ., ., 35]
  Reward_per_step: -1