Policy Iteration:
  plot_value_functions: True
  iterations: 10
  discount_factor: 0.999
  value_function_init: 0
  is_asynchronous: True
  policy_evaluation_threshold: !!float 1

Value Iteration:
  plot_value_functions: True
  iterations: 10
  discount_factor: 0.999
  value_function_init: 0
  is_asynchronous: True
  policy_evaluation_threshold: !!float 1

Sarsa:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1.0
  epsilon_decay: 0.999

Q-Learning:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1.0
  epsilon_decay: 0.999

On-Policy MC Control:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  epsilon: 1.0
  epsilon_decay: 0.999
  num_of_episodes_to_collect: 1
  use_every_visit: False
  step_size: null  # If null, true mean will be calculated
