Policy Iteration:
  plot_value_functions: True
  iterations: 10
  discount_factor: 0.999
  value_function_init: 0
  is_asynchronous: True
  policy_evaluation_threshold: !!float 1

Value Iteration:
  plot_value_functions: True
  iterations: 10
  discount_factor: 0.999
  value_function_init: 0
  is_asynchronous: True
  policy_evaluation_threshold: !!float 1

Sarsa:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1.0
  epsilon_decay: 0.999

ExpectedSarsa:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1.0
  epsilon_decay: 0.999

Q-Learning:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1.0
  epsilon_decay: 0.999

On-Policy MC Control:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  epsilon: 1.0
  epsilon_decay: 0.999
  num_of_episodes_to_collect: 1
  use_every_visit: False
  step_size: null  # If null, true mean will be calculated

Off-Policy MC Control:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  epsilon: 1
  epsilon_decay: 0.999
  num_of_episodes_to_collect: 5
  step_size: 0.2

n-step Sarsa:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1
  epsilon_decay: 0.999
  n: 4

Off-Policy n-step Sarsa:
  plot_returns: True
  plot_value_functions: False
  iterations: 10000
  discount_factor: 0.999
  value_function_init: 100.0
  step_size: 0.2
  epsilon: 1
  epsilon_decay: 0.99999
  n: 4

n-step Tree Backup:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  n: 4

Off-Policy n-step Q(sigma):
  plot_returns: True
  plot_value_functions: False
  iterations: 1000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 1
  epsilon_decay: 0.999
  n: 4
  sigma_strategy: tree_backup  # Possible values:  tree_backup, sarsa, alternating, random

Dyna-Q:
  plot_returns: True
  plot_value_functions: False
  iterations: 5000
  discount_factor: 0.999
  value_function_init: 0
  step_size: 0.2
  epsilon: 0.5
  epsilon_decay: 0.999
  planning_steps: 5